### ISSUE TITLE
Solutions week 9

### ISSUE THREAD

**Issue by Mehtab-Cheema26** [IbraTech04/FSG-Slides#1]
![image](https://github.com/IbraTech04/FSG-Slides/assets/69216606/6fb2f351-5c04-4a79-a69f-be2948b80200)

The max height that can be achieved is n since our definition for height states that height starts at 1.

**Comment by IbraTech04** [comment]
Correct, it appears that based on the CSC148 course definitions the answer should be $n$. I will update this accordingly

**Comment by IbraTech04** [comment]
Fixed with commit 101fcf1
